### LOGOUT
DELETE http://localhost:3000/authenticate/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTM5NjQ1MjAsImV4cCI6MTY1Mzk2NDU0MH0.Wom6Vu6v_9kimC5XoUij3w7mQJcnHtpExOG688syQYU"
}

### LOGIN ###
POST http://localhost:3000/authenticate/login
Content-Type: application/json

{
    "login": "Admin",
    "password": "1234567890"
}

### GERAR NOVA TOKEN ###
POST http://localhost:3000/authenticate/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTQwMDMyNjR9.J6fhvsZtWWcIoszvN7F9iryFJ98a9sgi1nsYtQk_uuM"
}

### REGISTRAR USUARIOS ###
POST http://localhost:3000/users/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTM5NjM4NjgsImV4cCI6MTY1Mzk2NjI2OH0.Z2iAJ6uTBGdMO9LcshvHTtDBCoOFgMWLsEBYSB72w7s

{
    "login": "Mahadeva",
    "password": "meukodix10",
    "role": "Admin"
}

### GERAR NOVO LEADTRACK ###
POST http://localhost:3000/leadtrack/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTQwMDMyOTEsImV4cCI6MTY1NDAwMzMxMX0.bueIGmd3CiZKe95OXkB_Kh-7VD4wXq6cM2SKQu-QwcE

{
    "name": "Eu",
    "email": "email@email.com",
    "tag_site": "tagasdwa",
    "tag": "YEAAAA",
    "city": "Ribeirao Amarelo",
    "phone_number": "321324234"
}

### LISTAR USUARIOS
GET http://localhost:3000/users/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTM5NjU5OTcsImV4cCI6MTY1Mzk2NjAxN30.dogzG8DgTq8U2fcIuujre31pcYYc81wzTjay9IJfCiY